DUNGEON_TABLES = {
    # Dungeon Aspects
    "history": [
        "Used by the original builders for its original purpose",
        "Used by the original builders, but eventually the site was taken over by invaders.",
        "Used by the original builders, but eventually the site was taken over by invaders. The invaders use the site"
        "for for another purpose.",
        "The dungeon has been occupied and abandoned several times, the original builders are long forgotten"
    ],
    "modifier": [
        "Rebel’s",
        "Verdant",
        "Hanging",
        "Sunken",
        "Crystal",
        "Magic",
        "Volcanic",
        "Maze",
        "Lovers",
        "Emperors",
        "Haunted",
        "Lichs",
        "Derelict",
        "Collapsed",
        "Icy",
        "Opulent",
        "Colossal",
        "Misty",
        "Wild",
        "Cave",
        "Lair",
        "Dragon",
        "Troll",
        "Goblin",
        "Drow",
        "Dwarven",
        "Elven",
        "Halfling",
        "Mountain",
        "Floating",
        "Arcane",
        "Druidic",
        "Lost",
        "Woad",
        "Bloody",
        "Sea",
        "Ethereal",
        "Spider",
        "Celestial",
        "Necro",
        "Wizard",
        "Abyssal",
        "Witch",
        "Defiled",
        "Ancient",
        "Thunder",
        "Amnesic",
        "Vast",
        "Mirrored",
        "Savage",
        "Sphinx",
        "Queen",
        "Slime",
        "Magical",
        "Carven",
        "Chronic",
        "Sacred",
        "Gilded",
        "Vampire",
        "Coastal",
        "Were",
        "Murder",
        "Monster",
        "Cosmic",
        "Fiery",
        "Abandon",
        "Weak",
        "Harpy",
        "Elder",
        "Cursed",
        "Astral",
        "Nomadic",
        "Under",
        "Spore",
        "Cult",
        "Phoenix",
        "Bandit",
        "Minotaur",
        "Arch mage",
        "Corpse",
        "Weird",
        "Eldritch",
        "Element",
        "Ogre",
        "Hidden",
        "Demonic",
        "Eternal",
        "Giant",
        "Clockwork",
        "Terrible",
        "Infested",
        "Mouldy",
        "Heretic",
        "Death",
        "Siren",
        "Mummy",
        "Golem",
        "Charnel",
        "Hallowed",
        "Royal",
        "Endless",
        "Faerie",
        "Griffon",
        "Puppet",
        "Eldritch",
        "Moonlit",
        "Stormy",
        "Basilisk",
        "Memnon",
        "Shune",
        "Primal",
        "Hag",
        "Kraken",
        "Medusa",
        "Naga",
        "Monster",
        "Rakshasa",
        "Rat",
        "Siren",
        "Ten-Eyed Oracle",
        "Merchant",
        "Viperian",
        "Priest",
        "Underworld",
        "Echoing",
        "War-torn",
        "Dreamy",
        "Spider",
        "Djinni",
        "Shadowy",
        "Angelic",
        "Magician",
        "Assassin",
        "Planar",
        "Mind",
        "Rogue",
        "Pirate",
        "Dinosaur",
        "Mystery",
        "Treetop",
        "Mimic",
        "Snowy",
        "Necrotic",
        "Forsaken",
        "Wailing",
        "Divine",
        "Feast",
        "Endless",
        "Wind",
        "Outsider",
        "Plague",
        "Frozen",
        "Fungal",
        "Animated",
        "Gorgon",
        "Legion",
        "Torment",
        "Knight",
        "Ominous",
        "Immortal",
        "Black",
        "Sanguine",
        "Velvet",
        "Candle",
        "Stone",
        "Wererat",
        "Buried",
        "Grinning",
        "Blind",
        "Magma",
        "Seaside",
        "Shifting",
        "Betrayer",
        "Skyward",
        "Onyx",
        "Otherworld",
        "Dark",
        "Guardian",
        "Insect",
        "Faceless",
        "Fiendish",
        "Duergar",
        "Resolute",
        "Fetid",
        "Harrowed",
        "Wyvern",
        "Amber",
        "Flooded",
        "Sultan’s",
        "Iron",
        "Chaos",
        "Glass",
        "Gede",
        "Orc",
        "Ooze",
        "Earthen",
        "Shadow",
        "Vampire",
        "Crumble",
        "Collapsed",
        "Damned",
        "Windy",
        "Saint",
        "Ancestor",
        "Unearth",
        "Rising",
        "Agony",
        "Ravaged",
        "Horrified",
        "Absurd",
        "Vital",
        "Runic",
        "Greedy",
        "Sorrowful",
        "Devious",
        "Cackling"
    ],
    "purpose": [
        "Mine",
        "Ruins",
        "Castle",
        "Shipwreck",
        "Caverns",
        "Forest",
        "Masoleum",
        "Sewers",
        "Pyramid",
        "Nexus",
        "Battlefield",
        "Workshop",
        "Tree",
        "Oasis",
        "Fortress",
        "Monastery",
        "Necropolis",
        "District",
        "Moor",
        "Bridge",
        "Glades",
        "Cave",
        "Undercity",
        "War Camp",
        "Academy",
        "Cairn",
        "City",
        "Prison",
        "Barrow",
        "Redoubt",
        "Monastery",
        "Plane",
        "Waterfall",
        "Catacomb",
        "Wilds",
        "Citadel",
        "Tavern",
        "Guild HQ",
        "Aerie",
        "Village",
        "Crypt",
        "Wasteland",
        "Tower",
        "Chasm",
        "Refuge",
        "Stilt Village",
        "Tomb",
        "Factory",
        "Menagerie",
        "Library",
        "Seraglio",
        "Palace",
        "Trenches",
        "Grove",
        "Gardens",
        "Keep",
        "Statue",
        "Woad",
        "Petra",
        "Market",
        "Zoo",
        "Nest",
        "Maze",
        "Forge",
        "Lighthouse",
        "Arena",
        "Cliff",
        "Colony",
        "Fane",
        "Mausoleum",
        "Airship",
        "Camp",
        "Lab",
        "Alchemist",
        "Temple",
        "Hideout",
        "Spire",
        "Shire",
        "Sanctuary",
        "Graveyard",
        "Sepulcher",
        "Brothel",
        "Dungeon",
        "Asylum",
        "Island",
        "Great Wall",
        "Feast Hall",
        "Shrine",
        "Portal",
        "Hell",
        "Underworld",
        "Mansion",
        "Hideaway",
        "Reservoir",
        "Domain",
        "Grotto",
        "Cove",
        "Foundry",
        "Oubliette",
        "Ossuary",
        "Barracks",
        "Courtyard",
        "Pits",
        "Court",
        "Roost",
        "Theatre",
        "Lair",
        "State",
        "Painted World",
        "Huts",
        "River",
        "Hoard",
        "Vault",
        "Abyss",
        "Warren",
        "Web",
        "Bazaar",
        "Chateau",
        "Manse",
        "Chambers",
        "Cathedral",
        "Abattoir",
        "Slum",
        "Reserve",
        "Retreat",
        "Headquarters",
        "Den",
        "Watchtower",
        "Party",
        "Burial Ground",
        "Realm",
        "Corridors",
        "Staircases",
        "Hunting Grounds",
        "Rift",
        "Trash Heap",
        "Alcazar",
        "Gorge",
        "Pass",
        "Peak",
        "Valley",
        "Caves",
        "Deeps",
        "Pools",
        "Creature",
        "Ziggurat",
        "Hive",
        "Bastion",
        "Circus",
        "Monolith",
        "Edifice",
        "Throne",
        "Gauntlet",
        "Trial",
        "Warcamp",
        "Hotel",
        "Archives",
        "Gate",
        "Reach",
        "Watch",
        "Quarry",
        "Cavern",
        "Glacier",
        "Ramparts",
        "Network",
        "Canals",
        "Halls",
        "Labyrinth",
        "Burrows",
        "Descent",
        "Delve",
        "Tower",
        "Row",
        "Hold",
        "Chapel",
        "Ravine",
        "Home",
        "Works",
        "Dimension",
        "Belfry",
        "Market",
        "Bulwarks",
        "Maw",
        "Hellgate",
        "Riddle",
        "Perch",
        "Hospital",
        "Ghost Ship",
        "Gallery",
        "Farm",
        "Teahouse",
        "Underpass",
        "Last Stand",
        "Sanctum",
        "Enclave",
        "Conclave",
        "Hills",
        "Hollow",
        "Tunnel",
        "Dugout",
        "Subterrane",
        "Chantry",
        "Cemetary",
        "Reliquary",
        "Grave",
        "Mound",
        "Museum",
        "Tribunal",
        "Chancery",
        "Consulate",
        "Colosseum",
        "Basilica",
        "Palazzo",
        "Arcology",
        "Villa",
        "Void"
    ],
    "ruin": [
        "Invasion. An enemy destroyed the dungeon.",
        "Civil War. Internal strife destroyed the dungeon.",
        "Poverty. The creators became too poor, and the dungeon fell to ruin.",
        "Famine. Lack killed the creators, and the dungeon fell to ruin.",
        "Disease. The disease killed the creators; the dungeon fell to ruin.",
        "Natural Disaster. Some natural disasters destroyed the dungeon: hurricanes, floods, and earthquakes.",
        "Hedonism. The creators devolved from some vice: drugs, slavery, or pleasure. The dungeon fell into disrepair.",
        "Magic. The dungeon was destroyed by magic.",
        "Powerful Monster. A powerful monster destroyed the dungeon."
    ],
    "present": [
        "Stronghold. The occupants are militant and have secured parts of the dungeon.",
        "Worship. The occupants use it for religious reasons.",
        "Enclave. The occupants use it as a place of magic research or experimentation.",
        "Industry. The occupants use it as a place of work. They are used to produce something.",
        "Redoubt. Occupants live here and try to avoid notice or don’t care to leave.",
        "Cursed. This place has fallen under a fell curse, and those that live here have no choice but to stay, and suffer."
    ],
}
FACTION_TABLES = {
    # Factions
    "goal": [
        "Domain. They are trying to consolidate power either in the dungeon or amongst themselves.",
        "Occult. They are seeking occult power.",
        "Excess. They want to enrich themselves with gold, food, pleasure, etc.",
        "Survival. They are trying to survive – either their resources or safety is threatened.",
        "Aspiration. They are trying to achieve something their society considers significant.",
        "Destruction. They seek to destroy something or someone.",
        "Evolution. They seek to evolve or change themselves to a superior state.",
        "Creation. They try to create new things and build.",
        "Freedom. They seek to escape from servitude or oppression."
    ],
    "obstacle": [
        "Fear. The faction or its leader fears committing to the goal and needs encouragement or assistance.",
        "Inept. The faction or its leader are inept and don’t know how or aren’t able to achieve their goal. Support, removal of obstacles, or leadership change are needed.",
        "Infighting. The faction is divided on achieving their goal and bicker amongst themselves. Some decisive sign to act needs to appear, or the dissenter needs to be removed.",
        "Opposed. Another faction actively impeds this one from achieving its goal.",
        "Norms. Some existential reason stops the faction from achieving its goal: breaking religious taboos, laws, or moral codes.",
        "Casualties. A sickness, lack of supplies or ongoing conflict have made the faction too weak to pursue their goal."
    ],
    "impulse": [
        "Capable",
        "Genuine",
        "Selfless",
        "Enthusiastic",
        "Sage",
        "Upright",
        "Dedicated",
        "Extraordinary",
        "Precise",
        "Prudent",
        "Stoic",
        "Sporting",
        "Cheerful",
        "Unfoolable",
        "Optimistic",
        "Modest",
        "Spontaneous",
        "Challenging",
        "Tolerant",
        "Athletic",
        "Self-defacing",
        "Articulate",
        "Casual",
        "Many-sided",
        "Realistic",
        "Debonair",
        "Meticulous",
        "Forgiving",
        "Tidy",
        "Directed",
        "Clear-headed",
        "Exciting",
        "Deep",
        "Captivating",
        "Scrupulous",
        "Perfectionist",
        "Reflective",
        "Neat",
        "Confident",
        "Observant",
        "Steady",
        "Moderate",
        "Kind",
        "Independent",
        "Responsive",
        "Patient",
        "Flexible",
        "Amiable",
        "Insightful",
        "Inoffensive",
        "Objective",
        "Farsighted",
        "Trusting",
        "Imaginative",
        "Self-critical",
        "Generous",
        "Venturesome",
        "Mature",
        "Innovative",
        "Orderly",
        "Chummy",
        "Attractive",
        "Purposeful",
        "Cultured",
        "Skillful",
        "Profound",
        "Curious",
        "Elegant",
        "Honourable",
        "Humorous",
        "Clean",
        "Allocentric",
        "Gentility",
        "Epitome",
        "Exultant",
        "Bohemian",
        "Prescient",
        "Governed",
        "Consultative",
        "Repudiative",
        "Laureate",
        "Mindful",
        "Neat",
        "Hospitable",
        "Benign",
        "Noble",
        "Fastidious",
        "Lovable",
        "Hardworking",
        "Sober",
        "Sweet",
        "Healthy",
        "Subtle",
        "Helpful",
        "Relaxed",
        "Efficient",
        "Aspiring",
        "Systematic",
        "Leisurely",
        "Good-natured",
        "Considerate",
        "Idealistic",
        "Daring",
        "Invulnerable",
        "Gentle",
        "Polished",
        "Self-denying",
        "Loyal",
        "Conciliatory",
        "Well-rounded",
        "Freethinking",
        "Logical",
        "Intelligent",
        "Secure",
        "Rational",
        "Playful",
        "Forceful",
        "Protean",
        "Well-bred",
        "Responsible",
        "Shrewd",
        "Sophisticated",
        "Protective",
        "Tractable",
        "Felicific",
        "Dutiful",
        "Youthful",
        "Friendly",
        "High-minded",
        "Providential",
        "Dignified",
        "Calm",
        "Thorough",
        "Forthright",
        "Fair",
        "Painstaking",
        "Strong",
        "Seraphic",
        "Earnest",
        "Sexy",
        "Passionate",
        "Ambitious",
        "Educated",
        "Undogmatic",
        "Humble",
        "Reliable",
        "Open",
        "Playful",
        "Nonauthoritarian",
        "Gracious",
        "Persuasive",
        "Contemplative",
        "Heroic",
        "Courteous",
        "Balanced",
        "Reverential",
        "Focused",
        "Companionly",
        "Winning",
        "Discreet",
        "Caring",
        "Urbane",
        "Respectful",
        "Uncomplaining",
        "Disciplined",
        "Multi-levelled",
        "Popular",
        "Compassionate",
        "Magnanimous",
        "Sociable",
        "Colourful",
        "Organized",
        "Sharing",
        "Conscientious",
        "Steadfast",
        "Charming",
        "Brilliant",
        "Anticipative",
        "Intuitive",
        "Firm",
        "Decisive",
        "Fun-loving",
        "Appreciative",
        "Simple",
        "Charismatic",
        "Constant",
        "Stable",
        "Empathetic",
        "Liberal",
        "Impressive",
        "Sympathetic",
        "Sane",
        "Understanding",
        "Eloquent",
        "Perceptive",
        "Cerebral",
        "Romantic",
        "Decent",
        "Warm",
        "Lyrical",
        "Leaderly",
        "Energetic",
        "Gallant",
        "Vivacious",
        "Punctual",
        "Dynamic",
        "Cooperative",
        "Hearty",
        "Faithful",
        "Knowledge",
        "Tasteful",
        "Personable",
        "Rustic",
        "Peaceful",
        "Clever",
        "Serious",
        "Absentminded",
        "Aggressive",
        "Ambitious",
        "Amusing",
        "Artful",
        "Ascetic",
        "Authoritarian",
        "Big-thinking",
        "Whimsical",
        "Breezy",
        "Businesslike",
        "Busy",
        "Casual",
        "Cerebral",
        "Chummy",
        "Circumspect",
        "Competitive",
        "Complex",
        "Confidential",
        "Conservative",
        "Contradictory",
        "Crisp",
        "Cute",
        "Deceptive",
        "Determined",
        "Dominating",
        "Dreamy",
        "Driving",
        "Droll",
        "Dry",
        "Earthy",
        "Effeminate",
        "Emotional",
        "Enigmatic",
        "Experimental",
        "Familial",
        "Folksy",
        "Formal",
        "Freewheeling",
        "Frugal",
        "Glamorous",
        "Guileless",
        "High-spirited",
        "Hurried",
        "Hypnotic",
        "Iconoclastic",
        "Idiosyncratic",
        "Impassive",
        "Impersonal",
        "Impressionable",
        "Intense",
        "Invisible",
        "Irreligious",
        "Irreverent",
        "Maternal",
        "Mellow",
        "Modern",
        "Moralistic",
        "Mystical",
        "Neutral",
        "Noncommittal",
        "Noncompetitive",
        "Obedient",
        "Old-fashioned",
        "Ordinary",
        "Outspoken",
        "Paternalistic",
        "Unsentimental",
        "Placid",
        "Political",
        "Predictable",
        "Preoccupied",
        "Private",
        "Progressive",
        "Proud",
        "Pure",
        "Questioning",
        "Quiet",
        "Religious",
        "Reserved",
        "Restrained",
        "Retiring",
        "Sarcastic",
        "Self-conscious",
        "Sensual",
        "Skeptical",
        "Smooth",
        "Soft",
        "Solemn",
        "Solitary",
        "Stern",
        "Unpredictable",
        "Strict",
        "Stubborn",
        "Stylish",
        "Subjective",
        "Surprising",
        "Soft",
        "Tough",
        "Unaggressive",
        "Unambitious",
        "Unceremonious",
        "Unchanging",
        "Undemanding",
        "Unfathomable",
        "Unhurried",
        "Uninhibited",
        "Unpatriotic",
        "Hairsplitting",
        "Attestant",
        "Idealized",
        "Commandable",
        "Grinchly",
        "Disingenuous",
        "Outpaced",
        "Logographic",
        "Hellenic",
        "Weepy",
        "Unwashen",
        "Grazier",
        "Stolid",
        "Endless",
        "Unexcelling",
        "Uncandid",
        "Acquiescent",
        "Textureless",
        "Susceptible",
        "Repurposing",
        "Ferreting",
        "Theatrical",
        "Recording",
        "Marred",
        "Fascinated",
        "Deferential",
        "Goitered",
        "Bungling",
        "Rallying",
        "Analytical",
        "Spewy",
        "Reconditioned",
        "Needful",
        "Exposed",
        "Anarchic",
        "Sentinel",
        "Overwhelmed",
        "Underwhelmed",
        "Inextensible",
        "Misaligned",
        "Reproachful",
        "Jeered",
        "Cantonal",
        "Servant",
        "Quitting",
        "Polytheistic",
        "Remorseful",
        "Introverted",
        "Stimulating",
        "Harebrained",
        "Thyestean",
        "Leasable",
        "Toadyish",
        "Tumultuous",
        "Wheedling",
        "Unmodest",
        "Bothersome",
        "Salacious",
        "Prescriptive",
        "Distorting",
        "Overreaching",
        "Crummy",
        "Placating",
        "Benign",
        "Seductive",
        "Subvertible",
        "Rigorous",
        "Clipt",
        "Overanimated",
        "Incognito",
        "Unmoored",
        "Persnickety",
        "Capricious",
        "Unsteady",
        "Volatile",
        "Constant",
        "Unshakeable",
        "Lax",
        "Judicious",
        "Half-witted",
        "Gung ho",
        "Foolhardy",
        "Laudible",
        "Invalid",
        "Disapproving",
        "Disgruntled",
        "Celibate",
        "Choosey",
        "Breaved",
        "Zen",
        "Wistful",
        "Wordly",
        "Wronged",
        "Vicious",
        "Vociferous",
        "Brazen",
        "Subdued",
        "Coveting",
        "Brooding",
        "Unreasonable",
        "Peculiar",
        "Indistinct",
        "Instigative",
        "Wolfish",
        "Toxic",
        "Swarthy",
        "Menacing",
        "Extravagant",
        "Unassuming",
        "Obvious",
        "Conspiratorial",
        "Loquacious",
        "Queer",
        "Vivacious",
        "Combative",
        "Garrulous",
        "Astute",
        "Auspicious",
        "Affluent",
        "Ambivalent",
        "Beguiling",
        "Obsequious",
        "Misanthropic",
        "Unhinged",
        "Convoluted",
        "Counterintuitive",
        "Intuitive",
        "Kindhearted",
        "Aspirational",
        "Deluded",
        "Glib",
        "Flighty",
        "Comedic",
        "Flustered",
        "Shellshocked",
        "Numb",
        "Destructive",
        "Convivial",
        "Antisocial",
        "Gregarious",
        "Infantile",
        "Inspirational",
        "Savage",
        "Ruthless",
        "Fiery",
        "False",
        "Conceited",
        "Miserable",
        "Uncreative",
        "Frightening",
        "Enervated",
        "Bewildered",
        "Venomous",
        "Shortsighted",
        "Mawkish",
        "Fanciful",
        "Aimless",
        "Airy",
        "Difficult",
        "Intolerant",
        "High-handed",
        "Shy",
        "Libidinous",
        "Disrespectful",
        "Phlegmatic",
        "Oppressed",
        "Hidebound",
        "Impatient",
        "Nihilistic",
        "Obsessive",
        "Indecisive",
        "Arrogant",
        "Uncooperative",
        "Careless",
        "Messy",
        "Unfriendly",
        "Fearful",
        "Cynical",
        "Envious",
        "Self-indulgent",
        "Plodding",
        "Dirty",
        "Possessive",
        "Blunt",
        "Melancholic",
        "Undisciplined",
        "Impractical",
        "Abrasive",
        "Anxious",
        "Foolish",
        "Pompous",
        "Flamboyant",
        "Petty",
        "Arbitrary",
        "Slow",
        "Stiff",
        "Gloomy",
        "Disconcerting",
        "Treacherous",
        "Perverse",
        "Superstitious",
        "Morbid",
        "Overimaginative",
        "Prim",
        "Timid",
        "Fatalistic",
        "Uncaring",
        "Miserly",
        "Fixed",
        "Obnoxious",
        "Assertive",
        "Obvious",
        "Provocative",
        "Regretful",
        "Faithless",
        "Brittle",
        "Outrageous",
        "Unstable",
        "Moody",
        "Paranoid",
        "Deceitful",
        "Superficial",
        "Misguided",
        "Uncharitable",
        "Unhealthy",
        "Cruel",
        "Gullible",
        "Troublesome",
        "Fraudulent",
        "Unreliable",
        "Fanatical",
        "Complacent",
        "Greedy",
        "Pretentious",
        "Unctuous",
        "Excitable",
        "Extravagant",
        "Tense",
        "Neglectful",
        "Pharisaical",
        "Pedantic",
        "Insecure",
        "Thievish",
        "Thoughtless",
        "Egocentric",
        "Inconsiderate",
        "Unrealistic",
        "Fawning",
        "Angry",
        "Cowardly",
        "Grim",
        "Strong-willed",
        "Secretive",
        "Presumptuous",
        "Submissive",
        "Disorganized",
        "Lazy",
        "Clumsy",
        "Dull",
        "Brutal",
        "Rigid",
        "Mechanical",
        "Devious",
        "Discourteous",
        "Shallow",
        "Irritable",
        "Reactive",
        "Decadent",
        "Weak-willed",
        "Prejudiced",
        "Haughty",
        "Ungrateful",
        "Dogmatic",
        "Ridiculous",
        "Complaintive",
        "Incurious",
        "Coarse",
        "Escapist",
        "Abrupt",
        "Childish",
        "Sadistic",
        "Mannered",
        "Naive",
        "Uncritical",
        "Conformist",
        "Unappreciative",
        "Imprudent",
        "Boisterous",
        "Argumentative",
        "Fickle",
        "Grand",
        "Bizarre",
        "Neurotic",
        "Ruined",
        "Dissolute",
        "Rowdy",
        "Dishonest",
        "Vague",
        "Disturbing",
        "Dependent",
        "Power-hungry",
        "Mistaken",
        "Domineering",
        "Contemptible",
        "Apathetic",
        "Irrational",
        "Asocial",
        "Mealymouthed",
        "Scornful",
        "Criminal",
        "Indulgent",
        "Repressed",
        "Stupid",
        "Predatory",
        "Extreme",
        "Calculating",
        "Unimaginative",
        "Desperate",
        "Vindictive",
        "Malicious",
        "Vulnerable",
        "Weak",
        "Irresponsible",
        "Discontented",
        "Inhibited",
        "Impulsive",
        "Distractible",
        "Profligate",
        "Silly",
        "Disruptive",
        "Callous",
        "Barbaric",
        "Venal",
        "Crude",
        "Compulsive",
        "Crass",
        "Resentful",
        "Odd",
        "Sloppy",
        "Critical",
        "Selfish",
        "Narrow-minded",
        "Confused",
        "Willful",
        "Procrastinating",
        "Tactless",
        "Ritualistic",
        "Regimental",
        "Graceless",
        "Scheming",
        "Forgetful",
        "Cold",
        "Destructive",
        "Astigmatic",
        "Aloof",
        "Loquacious",
        "Disputatious",
        "Demanding",
        "Muddle-headed",
        "Hesitant",
        "Insulting",
        "Frivolous",
        "Ignorant",
        "Vacuous",
        "Opinionated",
        "Suspicious",
        "Disobedient",
        "Meddlesome",
        "Hateful",
        "Hedonistic",
        "Repentant",
        "Insincere",
        "Expedient",
        "Sedentary",
        "Opportunistic",
        "Passive",
        "Sly",
        "Single-minded",
        "Sanctimonious",
        "Crazy",
        "Hostile",
        "Tasteless",
        "Monstrous",
        "Unprincipled",
        "One-dimensional",
        "Dissonant",
        "Wishful",
        "Narcissistic",
        "Imitative",
        "Crafty",
        "Disloyal",
        "Transparent",
        "Insensitive",
        "Erratic",
        "Amoral",
        "Cautious"
        ],
    "size": [
        "One powerful creature",
        "A small tight-knit group",
        "An unorganized gang",
        "A large group",
        "A vast collective"
        ],
    "creature_type": [
        "Beastial",
        "Insectoid",
        "Amphibian",
        "Goblinoid",
        "Humanoid",
        "Reptilian",
        "Viperian",
        "Undead",
        "Ghosts",
        "Crystalline Beings",
        "Stonehewn Beings",
        "Plant",
        "Ooze",
        "Demonic",
        "Devilish",
        "Outsider",
        "Monstrosity",
        "Angelic",
        "Magical Being",
        "Vermin",
        "Shapechanger",
        "Fey",
        "Immortal",
        "Draconic",
        "Homunculus",
        "Elven",
        "Dwarven",
        "Halfling",
        "Orcish",
        "Goblin",
        "Gnomish",
        "Human",
        "Old Ones",
        "Orderlings",
        "Chaos Servants",
        "Fairies",
        "Kytherians",
        "Parasites",
        "Thanians",
        "Aliens",
        "Time Travellers"
    ]
}
EXTERIOR_TABLES = {
    "environment": [
        "Ruined city",
        "Sewer",
        "Farm/Orchard",
        "Graveyard",
        "Ruined castle",
        "Temple",
        "Chasm",
        "Cliff face",
        "Desert",
        "Forest",
        "Glacier",
        "Gorge",
        "Jungle",
        "Mountain pass",
        "Swamp",
        "Mesa",
        "Caves",
        "Sea cave",
        "Mountain peak",
        "Island",
        "Underwater",
        "Treetop",
        "Behind waterfall",
        "Archaeological dig site",
        "Volcano caldera",
        "Deep underground",
        "Bottom of sinkhole",
        "Floating on sea",
        "On a cloud",
        "A pocket dimension",
        "Wasteland",
        "On/inside a giant creature",
        "Steppe",
        "Inside a book",
        "Re-roll twice and combine"
    ],
    "path": [
        "Patrolled. The path is controlled by a faction, there is a chance of random encounters.",
        "Hazard. The path is unstable or dangerous: rope bridge, or precarious trail, or crumbling stairs.",
        "Clear. The path allows for a good look at the dungeon.",
        "Clue. A spot along the path provides a clue to the dungeon ahead.",
        "Key. A spot along the path provides a key to the dungeon ahead.",
        "Boon. A spot along the path provides treasure or a boon."
    ],
    "path_patrolled": [
        "Powerful monster patrols its path as its hunting ground.",
        "Local monsters/wildlife/bandits unrelated to dungeon factions patrol the path as their hunting ground. May exact toll, exploit party, or attack.",
        "The dungeon faction patrols the path as their domain. Likely the dominant faction or one subservient to them. Roll or choose who. May exact toll, exploit party, or attack.",
        "Local civil authority patrolled to keep monsters contained or prevent looters from raiding dungeons. May exact toll, exploit party, or try to avoid them from accessing dungeon."
    ],
    "landmark": [
        "No landmark",
        "Natural feature",
        "Ruined structure",
        "Odd sound",
        "Odd smell",
        "Odd sight"
    ],
    "secondary_entrance_location": [
        "Hidden, found via clue",
        "Obvious, Opened via key",
        "Hidden, Only opens from the exterior",
        "Hidden, It only opens from the interior",
        "Open and obvious",
        "Open and obvious"
    ],
    "secondary_entrance_destination": [
        "First floor",
        "First floor",
        "Second floor",
        "Second floor or deeper",
        "Secret sub-level connected to main dungeon",
        "Directly to a treasure, somewhere"
    ],
    "antechamber": [
        "Supernatural. What about the entrance shows this dungeon is supernatural?",
        "Omen. What omen shows danger inhabits this place?",
        "Wealth. What about the entrance hints there is wealth to be had here?",
        "Death. What sign indicates those that enter here will die?",
        "Imposing Architecture. What fantastic piece of architecture shows this is no regular dungeon?"
    ]
}
CHALLENGE_TABLES = {
    "Hazard": [
        "Icy Floor",
        "Rubble"
    ],
    "clue": [
        "A clue to the dungeon",
        "A clue to the dungeon",
        "A clue to the dungeon",
        ],
    "key": [
        "A key to the dungeon",
        "A key to the dungeon",
        "A key to the dungeon",
    ],
},
TREASURE_TABLES = {
    "treasure": [
        "sack of gold",
        "trinket"
    ]
}
